[profile.release]
panic = "unwind"

[workspace]
members = [
	"integration-tests",
	"node",
	"pallets/*",
	"runtimes/*",
	"xcm-emulator"
]

[patch."https://github.com/paritytech/cumulus"]
xcm-emulator = { path = "xcm-emulator" }